### ISSUE TITLE
Issues with Lazy Mining

### ISSUE THREAD

**Issue by dhouck** [coandco/mafia-volcano-mining#2]
I'm having two issues with lazy mining:

1. Even though the lazy mining algorithm described doesn't require Object Detection, the script still needs it, and glancing at how the script works it looks like it still uses it in the calculation so I can't just apply a simple fix myself.
2. If you *do* have Object Detection and there are sparkles in the second row but not the first, it'll just mine a square in the first row and leave, instead of mining a square below the largest group of sparkles in the second row and trying them.

If you fix at least 1, then 2 will be less of an issue, but ideally both should be fixed. 2 looked like it would be a one-character change, but I'm new to ASH and this script looks complicated so I'm not sure.

**Comment by sensei1024** [comment]
2 is a bug in the "findCheapestSpot" method.  If there is an accessible sparkle in row 2 (because of mining), and an inaccessible sparkle later in row 2, the method will pick the latter, declare it inaccessible, and give up.

I've created a branch for that.


1 is true, and would require some changes to how the sparkles refresh.

**Comment by dhouck** [comment]
I think this was fixed by #3 but I wasn’t paying attention.  I just came back to KoL and noticed that there's a different lazy mining issue.
